name: Gitleaks scan

on:
  push:
    branches:
    - mains

jobs:
  gitleaks-codescan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Workflow detail api request
        shell: bash
        run: |
          echo "Ref name is $GITHUB_RUN_ID"
          echo "Source is ${{ github.server_url }}/${{ github.repository }}"
          echo "Subject is $GITHUB_WORKFLOW_REF|${{ github.run_id }}|${{ github.run_attempt }}|${{ github.run_number }}"
          echo "Job is $GITHUB_JOB"
          echo "Step id is ${{ steps.internal.id }}"

      - name: Gitleaks scan
        uses: cloudbees-io/gitleaks-github-test@main
        with:
          cloudbees-pat: ${{ secrets.CLOUDBEES_PROD_PAT }}

